#!/usr/bin/env python3
"""Render standalone Codex agents from the shared capacity catalog."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any, cast

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / ".codex" / "agent_catalog.toml"
AGENTS_DIRECTORY = REPO_ROOT / ".codex" / "agents"
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
CLASS_FIELDS = frozenset(
    {
        "description",
        "model",
        "model_reasoning_effort",
        "sandbox_mode",
        "approval_policy",
        "developer_instructions",
    }
)
SPECIALIST_FIELDS = frozenset(
    {
        "profile",
        "description",
        "sandbox_mode",
        "approval_policy",
        "developer_instructions",
    }
)
OUTPUT_FIELDS = (
    "name",
    "description",
    "model",
    "model_reasoning_effort",
    "sandbox_mode",
    "approval_policy",
)


def require_table(value: object, label: str) -> dict[str, Any]:
    """Require a TOML table."""
    if not isinstance(value, dict):
        raise TypeError(f"{label} must be a TOML table")
    return cast(dict[str, Any], value)


def require_fields(table: dict[str, Any], required: frozenset[str], label: str) -> None:
    """Require the supported non-empty string fields for a catalog entry."""
    missing = required - table.keys()
    extra = table.keys() - required
    if missing or extra:
        raise ValueError(
            f"{label} has invalid fields: missing={sorted(missing)}, extra={sorted(extra)}"
        )
    for key, value in table.items():
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{label}.{key} must be a non-empty string")


def validate_settings(table: dict[str, Any], label: str) -> None:
    """Reject unsupported permission settings before rendering."""
    if table.get("sandbox_mode") not in {None, "read-only", "workspace-write"}:
        raise ValueError(f"{label}.sandbox_mode must be read-only or workspace-write")
    if table.get("approval_policy") not in {None, "never", "on-request"}:
        raise ValueError(f"{label}.approval_policy must be never or on-request")


def render_agent(name: str, settings: dict[str, Any]) -> str:
    """Render one standalone agent with stable field order."""
    instructions = cast(str, settings["developer_instructions"])
    if '"""' in instructions:
        raise ValueError(f"{name}.developer_instructions contains a TOML delimiter")
    lines = [
        "# Generated by scripts/render_codex_agents.py; edit .codex/agent_catalog.toml.\n"
    ]
    for field in OUTPUT_FIELDS:
        value = name if field == "name" else settings[field]
        lines.append(f"{field} = {json.dumps(value, ensure_ascii=False)}\n")
    trimmed_instructions = instructions.rstrip("\n")
    lines.append(f'developer_instructions = """\n{trimmed_instructions}\n"""\n')
    return "".join(lines)


def render_catalog(catalog_path: Path) -> dict[str, str]:
    """Expand class and specialist entries into standalone agent files."""
    with catalog_path.open("rb") as catalog_file:
        catalog = require_table(tomllib.load(catalog_file), "catalog")
    if catalog.keys() != {"defaults", "classes", "specialists"}:
        raise ValueError(
            "catalog must contain defaults, classes, and specialists tables"
        )
    classes = require_table(catalog["classes"], "classes")
    specialists = require_table(catalog["specialists"], "specialists")
    defaults = require_table(catalog["defaults"], "defaults")
    if defaults.keys() != {"subagent_profile"}:
        raise ValueError("defaults must contain only subagent_profile")
    default_profile = defaults["subagent_profile"]
    if not isinstance(default_profile, str) or default_profile not in classes:
        raise ValueError("defaults.subagent_profile references an unknown class")
    if not classes or not specialists:
        raise ValueError("catalog must define classes and specialists")

    agents: dict[str, str] = {}
    for name, raw_class in classes.items():
        if NAME_PATTERN.fullmatch(name) is None:
            raise ValueError(f"invalid class name: {name}")
        agent_class = require_table(raw_class, f"classes.{name}")
        require_fields(agent_class, CLASS_FIELDS, f"classes.{name}")
        validate_settings(agent_class, f"classes.{name}")
        agents[name] = render_agent(name, agent_class)

    for name, raw_specialist in specialists.items():
        if NAME_PATTERN.fullmatch(name) is None or name in agents:
            raise ValueError(f"invalid or duplicate specialist name: {name}")
        specialist = require_table(raw_specialist, f"specialists.{name}")
        required = frozenset({"profile", "description", "developer_instructions"})
        missing = required - specialist.keys()
        extra = specialist.keys() - SPECIALIST_FIELDS
        if missing or extra:
            raise ValueError(
                f"specialists.{name} has invalid fields: missing={sorted(missing)}, extra={sorted(extra)}"
            )
        for key, value in specialist.items():
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"specialists.{name}.{key} must be a non-empty string")
        validate_settings(specialist, f"specialists.{name}")
        profile = cast(str, specialist["profile"])
        if profile not in classes:
            raise ValueError(f"specialists.{name} references unknown class: {profile}")
        settings = dict(require_table(classes[profile], f"classes.{profile}"))
        settings.update(
            {key: value for key, value in specialist.items() if key != "profile"}
        )
        agents[name] = render_agent(name, settings)

    return {
        name.replace("_", "-") + ".toml": content for name, content in agents.items()
    }


def main() -> int:
    """Check generated agents by default, or write them when requested."""
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        "--write", action="store_true", help="update generated agents"
    )
    arguments = parser.parse_args()
    try:
        expected = render_catalog(CATALOG_PATH)
        actual = {path.name: path for path in AGENTS_DIRECTORY.glob("*.toml")}
        unexpected = sorted(actual.keys() - expected.keys())
        if unexpected:
            raise ValueError(f"unexpected agent files: {', '.join(unexpected)}")
        stale = [
            name
            for name, content in expected.items()
            if name not in actual or actual[name].read_text(encoding="utf-8") != content
        ]
        if arguments.write:
            AGENTS_DIRECTORY.mkdir(parents=True, exist_ok=True)
            for name in stale:
                (AGENTS_DIRECTORY / name).write_text(expected[name], encoding="utf-8")
            print(f"Updated {len(stale)} agent file(s).")
            return 0
        if stale:
            print(f"Stale or missing agents: {', '.join(stale)}", file=sys.stderr)
            return 1
        print(f"All {len(expected)} agent files match the catalog.")
        return 0
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as error:
        print(f"Agent catalog error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
